[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
option = "nightcycle/option@^1"
result = "nightcycle/result@^1"
lune-util = "nightcycle/lune-util@^0"
