[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Result = "nightcycle/result@0.3.2"
Option = "nightcycle/option@0.2.0"
